resources:
  repositories:
    - repository: templates
      type: github
      name: dirigeants/pipelines
      endpoint: vladfrangu

jobs:
  - template: lint.yml@templates

  - job: Test Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'
      - script: yarn
        displayName: 'Install Dependencies'
      - script: 'yarn build'
        displayName: 'Test Build'
